### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by zhang-hang** [bzppx/bzppx-codepub#10]
Request Method: 	GET
Request URL: 	/
RemoteAddr: 	127.0.0.1
Stack

/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/home/phachon/code/github-go/src/bzppx-codepub/vendor/github.com/astaxie/beego/template.go:73
/home/phachon/code/github-go/src/bzppx-codepub/vendor/github.com/astaxie/beego/controller.go:256
/home/phachon/code/github-go/src/bzppx-codepub/vendor/github.com/astaxie/beego/controller.go:207
/home/phachon/code/github-go/src/bzppx-codepub/vendor/github.com/astaxie/beego/controller.go:187
/home/phachon/code/github-go/src/bzppx-codepub/install/controllers/base.go:53
/home/phachon/code/github-go/src/bzppx-codepub/install/controllers/install.go:21
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/reflect/value.go:434
/usr/local/go/src/reflect/value.go:302
/home/phachon/code/github-go/src/bzppx-codepub/vendor/github.com/astaxie/beego/router.go:816
/usr/local/go/src/net/http/server.go:2568
/usr/local/go/src/net/http/server.go:1825
/usr/local/go/src/runtime/asm_amd64.s:2197

beego 1.8.3 (beego framework)

golang version: go1.8.3

**Comment by phachon** [comment]
![image](https://user-images.githubusercontent.com/19726268/38534390-9c1df970-3cb0-11e8-973a-daeedcb1d092.png)
