### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by feige2018** [bzppx/bzppx-codepub#11]
1，登录验证码，去掉数字 0，1，字母  o，i，l，因为这几个老是混淆分不清。

2，创建一个普通用户，发布代码时，进度一直在转，0%， 新开窗口查看历史显示发布成功。

3，节点列表中，IP 右边加一列显示节点备注，这样才好辨认。

**Comment by snail007** [comment]
@yincongcyincong @phachon

**Comment by feige2018** [comment]
把登录超时时间写到配置文件里面。
