### ISSUE TITLE
ssh拉代码端口不是默认22时报错

### ISSUE THREAD

**Issue by feign** [bzppx/bzppx-codepub#15]
由于某些原因禁用了默认端口22，用codepub的时候还是找的默认端口22，哪里可以配置端口？
Result: publish code error: dial tcp x.x.x.x:22: getsockopt: connection refused

**Comment by snail007** [comment]
使用git clone命令clone项目时，如果repository的SSH端口不是标准22端口时（例如，SSH tunnel模式，等等），可以使用如下命令：
`git clone ssh://git@hostname:port/.../xxx.git`
举例如下：
`git clone ssh://git@10.107.200.113:2222/root/test.git`

**Comment by feign** [comment]
@snail007 如果是这样的话在  * 代码仓库 -> SSH -> 怎么配置？？ 操作失败：代码仓库地址必须是 git@ 开头！
