### ISSUE TITLE
发布项目的时候，发布到不同的节点服务，同时关闭服务，在开启服务，导致业务中断

### ISSUE THREAD

**Issue by tomlinux** [bzppx/bzppx-codepub#22]
发布项目的时候，发布到不同的节点服务，codepub-agent 执行服务启动和关闭，
前端的负载均衡tcp端口检测，同时摘除，导致业务中断。 各位遇到这样的问题没有

**Comment by snail007** [comment]
前置命令,随机sleep可以解决
